### ISSUE TITLE
Give proper credit to the creators of wait-for-it

### ISSUE THREAD

**Issue by thepabloaguilar** [arquivei/php-kafka-consumer#24]
The contents of `wait-for-it.sh` are identical (except for a final newline) to the original script, which you can check with:

```bash
cd "$(mktemp -d)"

git clone git@github.com:arquivei/php-kafka-consumer.git
git clone git@github.com:vishnubob/wait-for-it.git

diff php-kafka-consumer/wait-for-it.sh wait-for-it/wait-for-it.sh
```

The wait-for-it project is under the MIT License. Such a license implies that we should keep a licensing header for all the work that we didn't author, and we MUST comply with that.

I know that the original file didn't include the header, but let's be nice and credit the authors despite the absence in the original file.

**Comment by joesantos418** [comment]
You're absolutely right and it was a grave oversight on my end. Thank you very much for bringing this to our attention I will ensure that we fix that as soon as possible.
