### ISSUE TITLE
Erro ao clonar repositório

### ISSUE THREAD

**Issue by vivianequinaia** [arquivei/php-kafka-consumer#27]
Ao tentar clonar o repositório eu recebo o seguinte erro:

error: invalid path 'build/test/Dockerfile:php7.2-v1.5.2-3.0.5-6'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by joesantos418** [comment]
Qual comando vc utilizou? Acabei de tentar aqui:

```
$ git clone git@github.com:arquivei/php-kafka-consumer.git
Cloning into 'php-kafka-consumer'...
remote: Enumerating objects: 74, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 674 (delta 56), reused 39 (delta 30), pack-reused 600
Receiving objects: 100% (674/674), 105.23 KiB | 682.00 KiB/s, done.
```

tentei também:

```
$ git clone https://github.com/vivianequinaia/php-kafka-consumer.git
Cloning into 'php-kafka-consumer'...
remote: Enumerating objects: 74, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 674 (delta 56), reused 39 (delta 30), pack-reused 600
Receiving objects: 100% (674/674), 105.23 KiB | 637.00 KiB/s, done.
Resolving deltas: 100% (341/341), done.
```

e ambos funcionaram com sucesso.

**Comment by vivianequinaia** [comment]
Tentei o primeiro

**Comment by vivianequinaia** [comment]
$ git clone git@github.com:arquivei/php-kafka-consumer.git
Cloning into 'php-kafka-consumer'...
Warning: Permanently added the RSA host key for IP address  '' to the list of known hosts.
Enter passphrase for key '/c/Users/User/.ssh/id_rsa':
remote: Enumerating objects: 74, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 674 (delta 56), reused 39 (delta 30), pack-reused 600
Receiving objects: 100% (674/674), 105.23 KiB | 633.00 KiB/s, done.
Resolving deltas: 100% (341/341), done.
error: invalid path 'build/test/Dockerfile:php7.2-v1.5.2-3.0.5-6'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by joesantos418** [comment]
Você poderia retentar como o git diz na última linha, por favor?

`and retry with 'git restore --source=HEAD :/'`

**Comment by vivianequinaia** [comment]
Tinha tentando esse comando antes e não tinha funcionado.
Tentei novamente e deu certo, mas ele segue dando erros nos arquivos.
$ git restore --source=HEAD :/
error: invalid path 'build/test/Dockerfile:php7.2-v1.5.2-3.0.5-6'
error: invalid path 'build/test/Dockerfile:php7.2-v1.5.2-3.0.5-7'
error: invalid path 'build/test/Dockerfile:php7.2-v1.5.2-3.1.3-6'
error: invalid path 'build/test/Dockerfile:php7.2-v1.5.2-3.1.3-7'
error: invalid path 'build/test/Dockerfile:php7.2-v1.5.2-4.0.4-6'
error: invalid path 'build/test/Dockerfile:php7.2-v1.5.2-4.0.4-7'
error: invalid path 'build/test/Dockerfile:php7.3-v1.5.2-3.0.5-6'
error: invalid path 'build/test/Dockerfile:php7.3-v1.5.2-3.0.5-7'
error: invalid path 'build/test/Dockerfile:php7.3-v1.5.2-3.0.5-8'
error: invalid path 'build/test/Dockerfile:php7.3-v1.5.2-3.1.3-6'
error: invalid path 'build/test/Dockerfile:php7.3-v1.5.2-3.1.3-7'
error: invalid path 'build/test/Dockerfile:php7.3-v1.5.2-3.1.3-8'
error: invalid path 'build/test/Dockerfile:php7.3-v1.5.2-4.0.4-6'
error: invalid path 'build/test/Dockerfile:php7.3-v1.5.2-4.0.4-7'
error: invalid path 'build/test/Dockerfile:php7.3-v1.5.2-4.0.4-8'
error: invalid path 'build/test/Dockerfile:php7.4-v1.5.2-3.0.5-6'
error: invalid path 'build/test/Dockerfile:php7.4-v1.5.2-3.0.5-7'
error: invalid path 'build/test/Dockerfile:php7.4-v1.5.2-3.0.5-8'
error: invalid path 'build/test/Dockerfile:php7.4-v1.5.2-3.1.3-6'
error: invalid path 'build/test/Dockerfile:php7.4-v1.5.2-3.1.3-7'
error: invalid path 'build/test/Dockerfile:php7.4-v1.5.2-3.1.3-8'
error: invalid path 'build/test/Dockerfile:php7.4-v1.5.2-4.0.4-6'
error: invalid path 'build/test/Dockerfile:php7.4-v1.5.2-4.0.4-7'
error: invalid path 'build/test/Dockerfile:php7.4-v1.5.2-4.0.4-8'

**Comment by joesantos418** [comment]
Você está usando windows?

**Comment by vivianequinaia** [comment]
> Você está usando windows?

Infelizmente

**Comment by joesantos418** [comment]
Esse erro acontece porque o windows não permite certos caracteres em nomes de arquivos (provavelmente ":" é o problema aqui). Nesse caso precisamos alterar os nomes desses arquivos para algo que o windows permita. Vou fazer essa alteração em breve.
