### ISSUE TITLE
Undefined Property

### ISSUE THREAD

**Issue by vivianequinaia** [arquivei/php-kafka-consumer#30]
return (is_string($this->groupId) && strlen($this->groupId) > 1) ? $this->groupId : $this->config['groupId'];

Options class in  line 39.

The $config var isn't defined.

 Undefined property: Kafka\Consumer\Laravel\Console\Commands\PhpKafkaConsumer\Options::$config

  at vendor/arquivei/php-kafka-consumer/src/Laravel/Console/Commands/PhpKafkaConsumer/Options.php:40
     36▕     }
     37▕ 
     38▕     public function getGroupId(): string
     39▕     {
  ➜  40▕         return (is_string($this->groupId) && strlen($this->groupId) > 1) ? $this->groupId : $this->config['groupId'];
     41▕     }
     42▕ 
     43▕     public function getCommit(): ?string
     44▕     {

**Comment by fcoedno** [comment]
I believe this is a bug introduced at 68fd226c0c49163c21a142b6ee92c2867da620b4. We made a refactor to extract the options handling into this `Options` class but forgot to handle the `$config` parameter. The fix should be straightforward: Just add a $config argument to the Options class constructor, and when instantiating it at `PhpKafkaConsumerCommand:32` we should forward the config array:

```php
        $options = new Options($this->options(), $this->config);
```
