### ISSUE TITLE
对 illuminate/console 的依赖可以把版本升级一下么?

### ISSUE THREAD

**Issue by chen-wen** [arquivei/php-kafka-consumer#4]
rt; laravel都 7.x 了

**Comment by joesantos418** [comment]
Couldn't agree more

**Comment by andrelugomes** [comment]
@chen-wen We are splitting this lib. 

Laravel 7.x support here  (https://github.com/arquivei/php-kafka-laravel)  soon ...

**Comment by joesantos418** [comment]
I am sorry, chen-wen, we are currently focusing on other details, we hope to be able to cover more versions of Laravel as well as other dependencies, but we can't do it before adding tests and automated builds.
