### ISSUE TITLE
Create a license file

### ISSUE THREAD

**Issue by joesantos418** [arquivei/php-kafka-consumer#7]
Currently we don't have a license. I don't think I need to explain more here, just writing this as a reminder.

**Comment by andrelugomes** [comment]
@joesantos418 How about MIT?

https://choosealicense.com/licenses/mit/

**Comment by andrelugomes** [comment]
Reading BSD that is used by Platform... seems ok too

https://github.com/arquivei/foundationkit/blob/master/LICENSE.txt

**Comment by andrelugomes** [comment]
https://snyk.io/blog/mit-apache-bsd-fairest-of-them-all/ @joesantos418

**Comment by joesantos418** [comment]
> https://snyk.io/blog/mit-apache-bsd-fairest-of-them-all/ @joesantos418

"The disadvantage is that anyone can take software licensed under MIT, change the branding, and sell it as proprietary software."

Both are on pretty much the same level IMO, but because of the above I'm leaning more towards BSD.
